"""Templates for report generation.

The templates intentionally use Jinja whitespace-control markers
(``{%- ... -%}``) so the rendered Markdown tables do not contain blank
rows between data lines.
"""

from __future__ import annotations

MARKDOWN_TEMPLATE = """# CannaOmics AI - Analysis Report

**Run ID:** {{ run_id }}
**Target:** {{ target }}
**Date:** {{ date }}

## 1. Overview

- **Samples:** {{ n_samples }}
- **Features:** {{ n_features }}
- **Model:** {{ model_name }}

## 2. Model Performance

| Metric | Value |
|---|---|
{%- for metric, value in metrics.items() %}
| {{ metric }} | {{ "%.4f"|format(value) }} |
{%- endfor %}

## 3. Top Candidate Features (Top 10)

| Rank | Feature | Importance | SHAP | Biological Context |
|---|---|---|---|---|
{%- for cand in top_candidates %}
| {{ loop.index }} | {{ cand.feature }} | {{ "%.4f"|format(cand.importance_mean) }} | {% if cand.mean_abs_shap is not none and cand.mean_abs_shap == cand.mean_abs_shap -%}{{ "%.4f"|format(cand.mean_abs_shap) }}{%- else -%}N/A{%- endif %} | {{ cand.nearest_gene }} ({{ cand.genomic_region }}) |
{%- endfor %}

---
*Generated by CannaOmics AI v{{ version }}*
"""  # noqa: E501 - intentional long Jinja row keeps Markdown table on one line

