"""Templates for report generation."""


MARKDOWN_TEMPLATE = """# CannaOmics AI - Analysis Report
**Run ID:** {{ run_id }}
**Target:** {{ target }}
**Date:** {{ date }}

## 1. Overview
- **Samples:** {{ n_samples }}
- **Features:** {{ n_features }}
- **Model:** {{ model_name }}

## 2. Model Performance
{% for metric, value in metrics.items() %}
- **{{ metric }}**: {{ "%.4f"|format(value) }}
{% endfor %}

## 3. Top Candidate Features (Top 10)
| Rank | Feature | Importance | SHAP | Biological Context |
|---|---|---|---|---|
{% for cand in top_candidates %}
| {{ loop.index }} | {{ cand.feature }} | {{ "%.4f"|format(cand.importance_mean) }} | {% if cand.mean_abs_shap %}{{ "%.4f"|format(cand.mean_abs_shap) }}{% else %}N/A{% endif %} | {{ cand.nearest_gene }} ({{ cand.genomic_region }}) |
{% endfor %}

---
*Generated by CannaOmics AI v{{ version }}*
"""
